Implement API access control when fetching profiles
bcgov/platform-services-registry pull request #103
Opened 2020-10-08 23:41 UTC by sbathgate

Resolves issue #49. To achieve issue #73 Create a dashboard where the user can view their existing projects, an access control feature is necessary so a regular user can only access their profiles, while an administrator can access all profiles.

This PR implements an access control capability when requesting access to profiles:

- [X] Update fetchAllProjectProfiles() to include access control
- [X] Update fetchProjectProfile() to include access control
- [X] implement findProfilesByUserID() function
- [ ] profile unit testing
- [ ] update API docs

2020-10-13 18:24 UTC, jleach requested changes
Looking good. I think as part of this ticket you should do all the other endpoints. For example,  `updateProfileNamespace`. Lets get all the CRUD ops done in this one ticket.

2020-10-13 18:24 UTC, jleach commented on api/src/controllers/profile.ts
> +    if (user.id === results.userId || user.roles.includes('administrator')) {
I think I'd put "administrator" into `constants.ts`.

2020-10-13 18:24 UTC, jleach commented on api/src/controllers/profile.ts
> +    if (user.id === results.userId || user.roles.includes('administrator')) {
I generally prefer early returns to if/else where possible; I think it makes the code more readable and less error prone. For example, one could:
```
if (user.id !== results.userId || !user.roles.includes('administrator')) {
   throw errorWithCode('Unauthorized Access', 401);
}
```

And skip the else.

2020-10-13 18:24 UTC, jleach commented on api/src/controllers/profile.ts
> +      throw errorWithCode('Unauthorized Access', 401);
I don't think this error will make it out. It'll get caught by the catch below and replaced with `throw errorWithCode(message, 500)`; You probably need to check and re-throw.
```
if (err.code) {
  throw err
}
```

2020-10-13 21:47 UTC, sbathgate commented on api/src/controllers/profile.ts
> +      results = await ProfileModel.findProfilesByUserID(user.id);
Good catch. Adjusted to match camelCase use throughout site. Additionally caught other inconsistencies which I updated accordingly.

2020-10-15 14:52 UTC, jleach approved these changes

2020-10-15 18:23 UTC, merged