Rewrite registry landing
bcgov/platform-services-registry pull request #1087
Opened 2023-10-05 17:56 UTC by Amritpal-Nijjar

2023-10-11 18:28 UTC, Amritpal-Nijjar commented on app/login/page.tsx
>            </li>
test

2023-10-11 19:26 UTC, okanji requested changes

2023-10-11 20:54 UTC, Amritpal-Nijjar commented
- Removed the global style, and replaced it with tailwind as bullet points were not rendering properly
- Fixed my issue with the npm package
- properly escaped the apostrophe

2023-10-16 15:48 UTC, merged

2023-10-16 15:49 UTC, okanji commented
Great work!