db migration perpartion for new quota-size
bcgov/platform-services-registry pull request #578
Opened 2021-11-27 20:28 UTC by w8896699

2021-12-07 22:06 UTC, sbathgate requested changes
Few thing to look at here

2021-12-07 22:06 UTC, sbathgate commented on db/sql/V4.0__add_quota_reference.sql
> +
Lots of variation between line spacing here. Ensure new lines between blocks remain consistent.

2021-12-07 22:06 UTC, sbathgate commented on db/sql/V4.0__add_quota_reference.sql
> +    storage_pvc_count   SMALLINT NOT NULL,
Uppercase type here, doesn't match the rest.

2021-12-07 22:06 UTC, sbathgate commented on db/sql/V4.0__add_quota_reference.sql
> +END TRANSACTION;
no newline

2021-12-07 22:06 UTC, sbathgate commented on db/sql/V4.0__add_quota_reference.sql
> +    updated_at  timestamp DEFAULT CURRENT_TIMESTAMP(3)
that goes for multiple blocks below too.

2021-12-07 22:35 UTC, w8896699 commented on db/sql/V4.0__add_quota_reference.sql
> +ON CONFLICT (id) DO NOTHING;
It is because we might have `custom` quota size in the future, add this rule in case we create some duplicate name in the future.

2021-12-08 22:27 UTC, sbathgate requested changes
There are still plenty of indentation and line separation issues occurring in this file. Please manually review the final output after making lint changes to ensure everything is correct.

Regarding the indentation, you typically align all of the second column one tab width away (2 spaces is my preference) from the widest first column. Many of the values in this file are unnecessarily indented. I have included an example in ref_memory_quota block on line 26

2021-12-08 22:27 UTC, sbathgate commented on db/sql/V4.0__add_quota_reference.sql
> +    created_at          timestamp DEFAULT CURRENT_TIMESTAMP(3),
This comma is breaking
```suggestion
    updated_at          timestamp DEFAULT CURRENT_TIMESTAMP(3),
    created_at          timestamp DEFAULT CURRENT_TIMESTAMP(3)
```

2021-12-08 22:27 UTC, sbathgate commented on db/sql/V4.0__add_quota_reference.sql
> +);
```suggestion
CREATE TABLE IF NOT EXISTS ref_memory_quota (
    id               varchar(32) PRIMARY KEY,
    memory_requests  varchar(16) NOT NULL,
    memory_limits    varchar(16) NOT NULL,
    created_at       timestamp DEFAULT CURRENT_TIMESTAMP(3),
    updated_at       timestamp DEFAULT CURRENT_TIMESTAMP(3)
);
```

2021-12-08 23:27 UTC, sbathgate approved these changes
LGTM

2021-12-10 20:25 UTC, merged