Serve csv
bcgov/platform-services-registry pull request #618
Opened 2022-02-16 16:26 UTC by okanji

## What?
With this PR the CSV download button fetches all its data directly from the server instead of gathering data from the table already populated in the frontend app.
## Why?
Currently this works fine, but with plans to add pagination this will break the CSV download as only a subset of project data will exist in the table so we need to fetch all dashboard data from the server when we want to create the csv file.
## How?
There are no API changes in this PR, and there already exists the functionality to convert JSON into CSV in the front end. I have created two separate `dowloadCSv` functions that are passed to the `Table` components of both the **Project** and **Requested Project** tables that handle their respective data fetching from the API. This data then gets transformed into CSV format using the existing functionality in the front end. 

_Note:_ When pagination is created in the API, different endpoints should be created as to not break the endpoints that the csv download uses.

## Testing?
There are no API changes so no API tests are included.

Note: I created this function on top of my communications branch which has not yet been merged to master, that PR should be merged in first

2022-02-28 17:16 UTC, w8896699 requested changes
Just a small suggestion

2022-02-28 17:25 UTC, okanji commented on web/src/components/dashboard/ProjectDetails.tsx
> +      console.log(err);
I agree, it would be good to let the user know what the error is. I will make this change, thanks!

2022-02-28 19:37 UTC, okanji commented on web/src/components/dashboard/ProjectDetails.tsx
> +      console.log(err);
@w8896699, I have implemented this change, please see the commit below

2022-03-02 17:27 UTC, w8896699 approved these changes
Looks good to me!

2022-03-03 20:44 UTC, merged