Update deploy.yaml
bcgov/platform-services-registry pull request #710
Opened 2022-05-04 18:28 UTC by ShovelHand

I don't see the parameters to add urls to namespaces when I look at a pod in OpenShift, so I added the parameters to deploy.yaml. I'm actually kind of guess that this was what was missing, so here it is for your review.

2022-05-10 17:46 UTC, w8896699 commented
No, there's nothing todo with this deployment.yaml.  Change need to be made in https://github.com/bcgov-c/tenant-gitops-platform-registry/blob/c0762900a2dba9a259cf47dceef79baf2e4e97de/platform-registry-app/base/deployment.registry-api.yaml#L113.

2022-05-10 17:47 UTC, w8896699 commented
And as I mentioned in RC, we only need one URL for each cluster(currently you have 4)

2022-05-10 17:48 UTC, w8896699 requested changes
Please look at above two comments

2022-05-10 23:39 UTC, ShovelHand commented
So there's no doubt; you're idea is that we have two base  URLs, one for some Gold  namespace, and One for a silver namespace, then we just programatically add "-prod", or "-dev" or whatever to it as is appropriate, right @w8896699?

2022-05-11 01:54 UTC, w8896699 commented
Yes

2022-05-12 20:31 UTC, w8896699 requested changes
I suggest that you revert the previous commit and redo the whole task in a new pr as the whole logic now has been changed. https://github.com/bcgov/platform-services-registry/pull/672

2022-05-12 21:49 UTC, ShovelHand commented on api/src/controllers/quota.ts
> +    const goldUrl = process.env.GOLD_CLUSTER_URL || "";
Yes

2022-05-12 21:50 UTC, ShovelHand commented
I am not redoing this task as a new PR. That is a needless reproduction of effort on something that has already gone on for way too long.

2022-05-17 20:37 UTC, w8896699 requested changes
Almost there

2022-05-17 20:37 UTC, w8896699 commented on web/src/components/profileEdit/QuotaCard.tsx
> -import useRegistryApi from '../../hooks/useRegistryApi';
clean up function in useRegistryApi as well

2022-05-17 20:37 UTC, w8896699 commented on web/src/components/profileEdit/QuotaCard.tsx
> -import useRegistryApi from '../../hooks/useRegistryApi';
and in web/src/views/ProfileEdit.tsx

2022-05-17 20:37 UTC, w8896699 commented on api/src/router/routes/quota.ts
> +router.get("/namespaceUrls", asyncMiddleware(getClusterUrls));
Are we still need changes in api?

2022-05-17 22:25 UTC, ShovelHand commented
I took a good, close look, and I think we're all good now. I thought I'd get you to have a last look before merging @w8896699

2022-05-17 22:54 UTC, w8896699 approved these changes

2022-05-17 22:55 UTC, merged